on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'
      
    - name: ðŸ”¨ Build Project
      run: |
        npm install
        npm run build
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GIT_SERVER }}
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_PASSWORD }}
        protocol: ${{ secrets.GIT_PROTOCOL }}
        local-dir: .next,public/asset
        exclude: '**/*'
  
    - name: ðŸ”„ Edit .htaccess
      run: |
        ssh user@your-cpanel-server '
          echo "# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
          PassengerAppRoot \"/home/salampid/subway/salampid\"
          PassengerBaseURI \"/\"
          PassengerNodejs \"/home/salampid/nodevenv/subway/salampid/20/bin/node\"
          PassengerAppType node
          PassengerStartupFile server.js
          # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END" > .htaccess
        '