on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'
    
    - name: âš™ï¸ Reconfigure FTP Status
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.NODE_DIR }}
          ls
          find . -mindepth 1 ! -regex '\./public\(/.*\)?' -delete
          ls
          cd public
          ls
          find . -mindepth 1 ! -regex '\./storage\(/.*\)?' -delete
          ls
      
    - name: ðŸ”¨ Build Project
      run: |
        npm install
        npm run build
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GIT_SERVER }}
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_PASSWORD }}
        protocol: ${{ secrets.GIT_PROTOCOL }}
        timeout: 180000
        exclude: |
          app/**
          node_modules/**
          public/storage/**
          .git/**
          .github/**
          .eslintrc.json
          .next/cache/**
          .gitignore
          next-env.d.ts
          next.config.ts
          postcss.config.mjs
          README.md
          tailwind.config.ts
          tsconfig.json

    - name: ðŸ”„ Edit .htaccess
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ps aux | grep "${{ secrets.NODE_DIR }}" | awk '{print $2}' | head -n 1 | xargs kill -9
          source ${{ secrets.NODE_BIN }}/activate && cd ${{ secrets.NODE_DIR }}
          npm install
          cd ${{ secrets.SSH_DIR }}
          echo "# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
          PassengerAppRoot \"${{ secrets.NODE_DIR }}\"
          PassengerBaseURI \"/\"
          PassengerNodejs \"${{ secrets.NODE_BIN }}/node\"
          PassengerAppType node
          PassengerStartupFile server.js
          # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END" > .htaccess